# Generated by Django 3.0.4 on 2020-12-15 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celery_progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgressPersistant',
            new_name='ProgressPersistent',
        ),
    ]
