# Generated by Django 3.0.2 on 2020-12-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_progress', '0002_auto_20201215_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresspersistent',
            name='state',
            field=models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=15),
        ),
    ]
